language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
services:
  - postgresql
before_script:
  - createdb -O $USER $USER
  - psql -U $USER -d $USER -c "CREATE TABLE presidents (name VARCHAR(255), inauguration DATE, ordinal INTEGER)"
  - cat test/data/presidents.csv | psql -U $USER -d $USER -c "COPY presidents FROM STDIN ( FORMAT CSV, DELIMITER('|'), HEADER TRUE )"
